#!/bin/sh

usage()
{
    printf '%s: [-c CHROOT] PACKAGE...\n' "${0#**/}"
}

set -e -u
chroot=unstable
while getopts 'c:h' opt
do
    case "$opt" in
        c) chroot="$OPTARG";;
        h) usage; exit;;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
if [ $# -eq 0 ]
then
    usage >&2
    exit 1
fi
for package in "$@"
do
(schroot --directory / -c "$chroot" -u root -- sh -c "
set -e
apt-get install -yqq $package
update-alternatives --get-selections | sort > /var/lib/ua-selections
sed -i -e 's/ auto / manual /' /var/lib/ua-selections
update-alternatives --set-selections < /var/lib/ua-selections
apt-get install --reinstall -qq $package
update-alternatives --get-selections | sort | diff -b --label before --label after -u /var/lib/ua-selections -
" || echo FAILED) 2>&1 | tee ${package}.log
done

# vim:ts=4 sts=4 sw=4 et
